grpc:
  server:
    port: 59091
collector:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        key.serializer: org.apache.kafka.common.serialization.VoidSerializer
        value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
    topics:
      sensors-events: telemetry.sensors.v1
      hubs-events: telemetry.hubs.v1
      snapshots-events: telemetry.snapshots.v1